name: release-app

trigger:
    batch: true
    # branches:
    #     include:
    #     - main
    paths:
        include:
        - pipelines/templates/release-template.yml

variables:
- template: ../variables/variables.yml
- group: serviceConnections

stages:
- template: ../templates/release-template.yml
  # parameters:
  #   azServiceConnection: '$(azServiceConnection)' # Value is in the variable group