name: release-apps

resources:
    pipelines:
    - pipeline: apps-resources
      source: Jabdel4.TodoApp.Build.Apps
    

trigger:
    batch: true
    branches:
        include:
        - main
    paths:
        include:
        - TodoAppBackend/*
        - TodoAppClient/*
        - pipelines/templates/release-apps-template.yml
        - pipelines/releases/release-apps.yml

variables:
- template: ../variables/variables.yml
- group: serviceConnections

jobs:
- template: ../templates/release-apps-template.yml