name: release-apps

parameters:
- name: env
  type: string
  default: dev
  values:
  - dev
  - qa
  - prod

resources:
    pipelines:
    - pipeline: dropClient
      source: Jabdel4.TodoApp.Build.Client
      trigger: true # To trigger a run when any run of the referenced pipeline completes    
    - pipeline: dropApi
      source: Jabdel4.TodoApp.Build.Api
      trigger: true # To trigger a run when any run of the referenced pipeline completes
    
trigger: none

variables:
- template: ../variables/variables.${{ parameters.env }}.yml
- group: serviceConnections

stages:
${{ if eq(parameters.env, 'dev')}}:
- stage: ${{ paramaters.env }}-stage
  condition: and(eq(variables['Build.SourceBranchName'], 'main', eq(variables['System.debug'], true))
  jobs:
  - template: ../templates/release-apps-template.yml
    parameters:
        env: ${{ paramaters.env }}

${{ elseif eq(parameters.env, 'qa')}}:
- stage: ${{ paramaters.env }}-stage
  dependsOn: dev
  condition: and(succeeded(), eq(variables['System.debug'], true))
  jobs:
  - template: ../templates/release-apps-template.yml
    parameters:
        env: ${{ paramaters.env }}

${{ elseif eq(parameters.env, 'prod')}}:
- stage: ${{ paramaters.env }}-stage
  dependsOn:
  - dev
  - qa
  condition: and(succeeded(), eq(variables['System.debug'], true))
  jobs:
  - template: ../templates/release-apps-template.yml
    parameters:
        env: ${{ paramaters.env }}

${{ else }}:
- stage: foo
  displayName: Parameter not found
  jobs:
  - job: foo-pm
    displayName: Error
    steps:
    - script: echo "Paremeter Not Found. Admitted values are {'dev', 'qa', 'prod'}"