name: release-infra

trigger:
    batch: true
    branches:
        include:
        - main
    paths:
        include:
        - pipelines/templates/release-infra-template.yml

variables:
- template: ../variables/variables.yml
- group: serviceConnections

jobs:
- template: ../templates/release-infra-template.yml
  # parameters:
  #   azServiceConnection: '$(azServiceConnection)' # Value is in the variable group