name: release-infra

parameters:
- name: Environment
  type: string
  values:
  - dev
  - qa
  - prod

trigger:
    batch: true
    branches:
        include:
        - main
    paths:
        include:
        - pipelines/templates/release-infra-template.yml

variables:
- template: ../variables/variables.${{ parameters.Environment}}.yml
- group: serviceConnections

jobs:
- template: ../templates/release-infra-template.yml