name: release-apps

parameters:
- name: Environment
  type: string
  values:
  - dev
  - qa
  - prod

resources:
    pipelines:
    - pipeline: dropClient
      source: Jabdel4.TodoApp.Build.Client
      trigger: true # To trigger a run when any run of the referenced pipeline completes    
    - pipeline: dropApi
      source: Jabdel4.TodoApp.Build.Api
      trigger: true # To trigger a run when any run of the referenced pipeline completes
    
trigger: none

variables:
- template: ../variables/variables.${{ parameters.Environment }}.yml
- group: serviceConnections

stages:
# - ${{ if eq(parameters.Environment, 'dev')}}:
- stage: ${{ parameters.Environment }}_stage
  condition: eq(variables['System.debug'], true))
  jobs:
    - template: ../templates/release-apps-template.yml
      parameters:
        Environment: ${{ parameters.Environment }}

# - ${{ elseif eq(parameters.Environment, 'qa')}}:
- stage: ${{ parameters.Environment }}_stage
  dependsOn: dev
  condition: and(succeeded(), eq(variables['System.debug'], true))
  jobs:
    - template: ../templates/release-apps-template.yml
      parameters:
        Environment: ${{ parameters.Environment }}

# - ${{ elseif eq(parameters.Environment, 'prod')}}:
- stage: ${{ parameters.Environment }}_stage
  dependsOn:
    - dev
    - qa
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'), eq(variables['System.debug'], true))
  jobs:
    - template: ../templates/release-apps-template.yml
      parameters:
        Environment: ${{ parameters.Environment }}

# - ${{ else }}:
#     - stage: foo
#       displayName: Parameter not found
#       jobs:
#       - job: foo-pm
#         displayName: Error
#         steps:
#         - script: echo "Parameter Not Found. Admitted values are {'dev', 'qa', 'prod'}"