name: release-apps

resources:
    pipelines:
    - pipeline: dropClient
      source: Jabdel4.TodoApp.Build.Client
      trigger: true # To trigger a run when any run of the referenced pipeline completes    
    - pipeline: dropApi
      source: Jabdel4.TodoApp.Build.Api
      trigger: true # To trigger a run when any run of the referenced pipeline completes
    
trigger: none

variables:
- template: ../variables/variables.yml
- group: serviceConnections

jobs:
- template: ../templates/release-apps-template.yml
  parameters:
    env: ''
# - template: ../templates/release-apps-template.yml
#   parameters:
#     env: 'qa'
# - template: ../templates/release-apps-template.yml
#   parameters:
#     env: 'prod'
