name: release-apps

resources:
    pipelines:
    - pipeline: apps-resources
      source: Jabdel4.TodoApp.Build.Apps
      trigger: true # To trigger a run when any run of the referenced pipeline completes
    
trigger: none

variables:
- template: ../variables/variables.yml
- group: serviceConnections

jobs:
- template: ../templates/release-apps-template.yml
#   parameters:
#     env: 'dev'
# - template: ../templates/release-apps-template.yml
#   parameters:
#     env: 'qa'
# - template: ../templates/release-apps-template.yml
#   parameters:
#     env: 'prod'
