name: delete-resources

trigger: none

variables:
- template: ../variables/variables.$(env).yml
- group: serviceConnections

pool:
    vmImage: $(vmImage)

steps:
- template: ../templates/undeploy-template.yml
  # parameters:
  #   azServiceConnection: '$(azServiceConnection)'