name: delete-resources

parameters:
- name: Environment
  type: string
  values:
  - dev
  - qa
  - prod

trigger: none

variables:
- template: ../variables/variables.${{ parameters.Environment }}.yml
- group: serviceConnections

pool:
    vmImage: $(vmImage)

steps:
- template: ../templates/undeploy-template.yml
  # parameters:
  #   azServiceConnection: '$(azServiceConnection)'