name: delete-resources

parameters:
- name: env
  type: string
  default: dev
  values:
  - dev
  - qa
  - prod

trigger: none

variables:
- template: ../variables/variables.${{ parameters.env }}.yml
- group: serviceConnections

pool:
    vmImage: $(vmImage)

steps:
- template: ../templates/undeploy-template.yml
  # parameters:
  #   azServiceConnection: '$(azServiceConnection)'