parameters:
- name: azServiceConnection
  type: string
  default: ''

stages:
- stage: RESOURCES
  jobs:
  - job: Infra
    steps:
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Bicep Resources'
          inputs:
            buildType: 'specific'
            artifactName: 'resources'
            targetPath: $(Pipeline.Workspace)
            project: 'DevOps Project'
            definition: 7
            buildVersionToDownload: 'latest'
        - task: ManualValidation@0
          displayName: 'Manual Validation'
          inputs:
            notifyUsers: |
                jorisbootcamp@outlook.com
                jobalos95@outlook.com
            instructions: 'Please. Ensure that the Azure Subscription is ready before deployment into the resource group $(resourceGroupName)'
            timeoutInMinutes: 15
            onTimeout: 'reject'
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Provision Azure'
          inputs:
            deploymentScope: "Resource Group"
            azureResourceManagerConnection: "${{ parameters.azServiceConnection }}"
            action: "Create Or Update Resource Group"
            resourceGroupName: "$(resourceGroupName)"
            location: "$(location)"
            templateLocation: "Linked artifact"
            csmFile: "$(templateFilePath)"
            csmParametersFile: "$(templateParametersFilePath)"
            deploymentMode: "Incremental"
            deploymentName: "DeployPipelineTemplate"
# - stage: APP
#   condition: onSucceeded('RESOURCES')
#   jobs:
#   - job: API
#     displayName: 'Deploy the API'
#     steps:
#         - task:
#   - job: CLIENT
#     displayName: 'Deploy the Client'
#     steps:
#       - task:
      