# parameters:
# - name: azServiceConnection
#   type: string
#   default: ''

stages:
- stage: RESOURCES
  jobs:
  - job: manualValidation
    displayName: 'Wait for Manual Validation'
    pool: server
    timeoutInMinutes: 15
    steps:
        - task: ManualValidation@0
          displayName: 'Manual Validation'
          inputs:
            notifyUsers: |
                jorisbootcamp@outlook.com
                jobalos95@outlook.com
            instructions: 'Please, ensure that bicep files are good before the provisioning.'
            timeoutInMinutes: 5
            onTimeout: 'reject'
  - job: Infra
    displayName: 'Azure Provisioning'
    dependsOn: manualValidation
    steps:
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Bicep Resources'
          inputs:
            buildType: 'specific'
            artifactName: 'resources'
            targetPath: $(Pipeline.Workspace)
            project: 'DevOps Project'
            definition: 7
            buildVersionToDownload: 'latest'
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Provision Azure'
          inputs:
            deploymentScope: "Resource Group"
            azureResourceManagerConnection: '$(azServiceConnection)'
            action: "Create Or Update Resource Group"
            resourceGroupName: "$(resourceGroupName)"
            location: "$(location)"
            templateLocation: "Linked artifact"
            csmFile: "$(templateFilePath)"
            csmParametersFile: "$(templateParametersFilePath)"
            deploymentMode: "Incremental"
            deploymentName: "DeployPipelineTemplate"

# - stage: APP
#   condition: onSucceeded('RESOURCES')
#   jobs:
#   - job: API
#     displayName: 'Deploy the API'
#     steps:
#         - task:
#   - job: CLIENT
#     displayName: 'Deploy the Client'
#     steps:
#       - task:
      