jobs:
  - job: Artifacts
    displayName: 'Download Artifacts'
    pool:
        vmImage:($vmImage)
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Client artifact'
      inputs:
        buildType: 'specific'
        project: '4eb0d06e-cb70-453b-8722-6c23f0ef15d7'
        definition: '6'
        buildVersionToDownload: 'latest'
        artifactName: 'client'
        targetPath: '$(Pipeline.Workspace)'    
    - task: DownloadPipelineArtifact@2
      displayName: 'Api artifact'
      inputs:
        buildType: 'specific'
        project: '4eb0d06e-cb70-453b-8722-6c23f0ef15d7'
        definition: '5'
        buildVersionToDownload: 'latest'
        artifactName: 'api'
        targetPath: '$(Pipeline.Workspace)'

  - job: manualValidation
    dependsOn: Artifacts
    displayName: 'Wait for Manual Validation'
    pool: server
    timeoutInMinutes: 15
    steps:
        - task: ManualValidation@0
          displayName: 'Manual Validation'
          inputs:
            notifyUsers: |
                jorisbootcamp@outlook.com
                jobalos95@outlook.com
            instructions: 'Do we need to deploy ? The App services should be stopped.'
            timeoutInMinutes: 5
            onTimeout: 'reject'

  - job: deployArtifactsToAppService
    displayName: 'Artifacts to App Services'
    dependsOn: manualValidation
    pool:
        vmImage: ($vmImage)
    steps:
        - task: AzureAppServiceManage@0
          displayName: 'Stop Api App Service'
          inputs:
            azureSubscription: '$(azServiceConnection)'
            Action: 'Stop Azure App Service'
            WebAppName: 'api-wapp-todoapp'
        - task: AzureAppServiceManage@0
          displayName: 'Stop Client App Service'
          inputs:
            azureSubscription: '$(azServiceConnection)'
            Action: 'Stop Azure App Service'
            WebAppName: 'client-wapp-todoapp'
        - task: AzureWebApp@1
          displayName: 'Deploy API'
          inputs:
            azureSubscription: '$(azServiceConnection)'
            appType: 'webAppLinux'
            appName: 'api-wapp-todoapp'
            package: '$(Pipeline.Workspace)/api.zip'
            runtimeStack: 'DOTNETCORE|7.0'
        - task: AzureWebApp@1
          displayName: 'Deploy Client'
          inputs:
            azureSubscription: '$(azServiceConnection)'
            appType: 'webAppLinux'
            appName: 'client-wapp-todoapp'
            package: '$(Pipeline.Workspace)/client.zip'
            runtimeStack: 'NODE|18-LTS'
        - task: AzureAppServiceManage@0
          displayName: 'Start Api App Service'
          inputs:
            azureSubscription: '$(azServiceConnection)'
            Action: 'Start Azure App Service'
            WebAppName: 'api-wapp-todoapp'
        - task: AzureAppServiceManage@0
          displayName: 'Start Client App Service'
          inputs:
            azureSubscription: '$(azServiceConnection)'
            Action: 'Start Azure App Service'
            WebAppName: 'api-wapp-todoapp'