name: build-infra

trigger:
   batch: true
   paths:
       include:
           - pipelines/infra/*
           - pipelines/builds/build-infra.yml
           - pipelines/templates/build-infra-template.yml

pool:
   vmImage: $(vmImage)

variables:
    - template: ../variables/variables.yml

steps:
   - template: ../templates/build-infra-template.yml