name: build-client

parameters:
- name: Environment
  type: string
  values:
  - dev
  - qa
  - prod

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - pipelines/templates/build-client-template.yml
    - TodoAppClient/*
    exclude:
    - README.md
    - .gitignore

variables:
- template: ../variables/variables.${{ parameters.Environment }}.yml

jobs:
- template: ../templates/build-client-template.yml