name: build-client


trigger:
  batch: true
  # branches:
  #   include:
  #   - main
  #   #- feature/todo-client
  paths:
    include:
    - pipelines/builds/build-client.yml
    - TodoAppClient/*
    exclude:
    - README.md
    - .gitignore

variables:
- template: ../variables/variables.yml

jobs:
- template: ../templates/build-client-template.yml