name: build-infra

parameters:
- name: env
  type: string
  default: dev
  values:
  - dev
  - qa
  - prod

trigger:
   batch: true
   paths:
       include:
           - pipelines/infra/*
           - pipelines/builds/build-infra.yml
           - pipelines/templates/build-infra-template.yml

pool:
   vmImage: $(vmImage)

variables:
    - template: ../variables/variables.${{ paramaters.env }}.yml

steps:
   - template: ../templates/build-infra-template.yml