name: build-client


trigger:
  batch: true
  branches:
    include:
    - main
    #- feature/todo-client
  paths:
    include:
    - pipelines/templates/build-client-template.yml
    - TodoAppClient/*
    exclude:
    - README.md
    - .gitignore

variables:
- template: ../variables/variables.$(env).yml

jobs:
- template: ../templates/build-client-template.yml