name: build-apps

parameters:
- name: Environment
  type: string
  values:
  - dev
  - qa
  - prod

trigger:
    batch: true
    branches:
        include:
        - main
    paths:
        include:
            - pipelines/templates/build-apps-template.yml
            - pipelines/build/build-apps.yml
        exclude:
            - README.md
            - .gitignore
            - .dockerignore

variables:
- template: ../variables/variables.${{ parameters.Environment }}.yml

pool:
    vmImage: $(vmImage)

steps:
- template: ../templates/build-apps-template.yml    